<?xml version="1.0" encoding="utf-8"?><Database Name="JFG_MST" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=YMGW-PC\SQLEXPRESS;Initial Catalog=JFG_MST;Persist Security Info=True;User ID=sa" SettingsObjectName="scheDataDelete.Properties.Settings" SettingsPropertyName="JFG_MSTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.会員情報" Member="会員情報">
    <Type Name="会員情報">
      <Column Name="カード番号" Type="System.Double" DbType="Float NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="本人最終記入日" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="更新年月日" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="氏名" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="フリガナ" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="生年月日" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="年令" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="性別" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="言語1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="言語名1" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="言語2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="言語名2" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="言語3" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="言語名3" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="言語4" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="言語名4" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="言語5" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="言語名5" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="合格年1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="合格年2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="合格年3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="合格年4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="合格年5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="免取県1" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免取県2" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免取県3" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免取県4" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免取県5" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免許番号1" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免許番号2" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免許番号3" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免許番号4" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="免許番号5" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="郵便番号" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="住所1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="住所2" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="住所3" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="地域コード" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="地域名" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="東西" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="自宅電話番号" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="自宅FAX番号" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="携帯電話番号" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="連絡可能時間" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="他連絡先" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="緊急連絡先" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="メールアドレス1" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="メールアドレス2" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="個人HP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="最寄駅1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="最寄駅2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="最寄駅3" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="就業可能条件" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="宿泊可否" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ガイド就業意思" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ガイド就業意思名" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="ガイド経験年数" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="ガイド経験地域1" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ガイド経験地域2" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ガイド経験地域3" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ガイド経験地域4" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ガイド経験分野1" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ガイド経験分野2" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ガイド経験分野3" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="ガイド経験分野4" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="新人研修" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="JFG関東45" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="JFG関東23" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="JFG関西45" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="JFG関西23" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="JGA関東" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="JGA関西" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ハロー研修" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="JICA区分" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JICA研修" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="IHCSA区分" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IHCSA研修" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="通訳就業意思" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="通訳就業意思名" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="通訳経験年数" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="通訳経験分野1" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="通訳経験分野2" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="通訳経験分野3" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="通訳経験分野4" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="英語以外語学検定" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="英語通訳検定" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="英検" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="国連英検" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="TOEIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOEFL" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="同時通訳可否区分" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="同時通訳可否" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="通訳訓練機関名" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="翻訳就業意思" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="翻訳就業意思名" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="翻訳経験年数" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="翻訳分野1" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="翻訳分野2" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="翻訳分野3" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="翻訳分野4" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="翻訳訓練機関" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ネイティブ可区分" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ネイティブ可" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="パソコン機種" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ソフト種類" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="パソコンOS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="海外添乗就業意思" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="海外添乗就業意思名" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="海外添乗経験年数" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="海外添乗地域1" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="海外添乗地域2" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="海外添乗地域3" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="海外添乗地域4" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="旅行主任取扱資格" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="旅程管理資格" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="他資格" Type="System.String" DbType="NVarChar(180)" CanBeNull="true" />
      <Column Name="職歴" Type="System.String" DbType="NVarChar(180)" CanBeNull="true" />
      <Column Name="学歴" Type="System.String" DbType="NVarChar(180)" CanBeNull="true" />
      <Column Name="趣味特技" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="自己PR" Type="System.String" DbType="NVarChar(180)" CanBeNull="true" />
      <Column Name="業務研修案内関東" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="業務研修案内関西" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="所属委員会1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="所属委員会名1" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="所属委員会2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="所属委員会名2" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="所属委員会3" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="所属委員会名3" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="賦課金支払2001" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="賦課金支払2002" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="賦課金支払2003" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="賦課金支払2004" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="賦課金支払2005" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="総会出欠状況2001" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="総会出欠状況2002" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="総会出欠状況2003" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="総会出欠状況2004" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="総会出欠状況2005" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="手数料合計2001" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="手数料合計2002" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="手数料合計2003" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="手数料合計2004" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="手数料合計2005" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="JFG加入年" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JFG加入月" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NP初回" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NP最終" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JFG会員歴" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JGA会員歴" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JFG休会年" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JFG休会月" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JFG退会年" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JFG退会月" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="出資証券番号" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="旧姓" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="HP顔写真" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="HP氏名" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="HP言語" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="HP合格" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="HP居住地" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="HPJFG" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="母国語1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="母国語名1" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="母国語2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="母国語名2" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="母国語3" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="母国語名3" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="メーリングリスト" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="HP掲載可否" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="国籍" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="昨年稼働日数" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GICSS研修" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="GICSS会員歴" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="KIGA会員歴" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="COG会員歴" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="JFG2日間机上" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="IJCEE会員歴" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ガイド関係団体" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="都道府県" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="登録年月日" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="変更年月日" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.会員稼働予定" Member="会員稼働予定">
    <Type Name="会員稼働予定">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="カード番号" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="年" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="月" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="フリガナ" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="アサイン区分" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="稼働年" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="稼働日数" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="自己申告年" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="自己申告日数" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="申告年月日" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="d1" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d2" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d3" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d4" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d5" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d6" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d7" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d8" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d9" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d10" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d11" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d12" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d13" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d14" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d15" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d16" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d17" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d18" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d19" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d20" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d21" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d22" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d23" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d24" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d25" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d26" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d27" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d28" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d29" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d30" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="d31" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="備考" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="更新日" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>