//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jfgSchedule.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGOneDrive\\")]
        public string xlsxPath {
            get {
                return ((string)(this["xlsxPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Log.txt")]
        public string logFileName {
            get {
                return ((string)(this["logFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\稼働予定表Temp.xlsx")]
        public string xlsKadouPath {
            get {
                return ((string)(this["xlsKadouPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\稼働予定表.xlsx")]
        public string xlsWorksPath {
            get {
                return ((string)(this["xlsWorksPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\ワークシート.xlsx")]
        public string xlsTempPath {
            get {
                return ((string)(this["xlsTempPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YMGW-PC\\SQLEXPRESS")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqlpass")]
        public string Pass {
            get {
                return ((string)(this["Pass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JFG_MST")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\新ホテル向けガイド稼働予定表.xlsx")]
        public string xlsHotelsWorksPath {
            get {
                return ((string)(this["xlsHotelsWorksPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\ホテル向けガイドリスト(英語) 2022.xlsx")]
        public string xlsHotelGuideListPath {
            get {
                return ((string)(this["xlsHotelGuideListPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\新ホテル向けガイドリスト.xlsx")]
        public string xlsNewHotelGuideListPath {
            get {
                return ((string)(this["xlsNewHotelGuideListPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\ホテル稼働予定表Temp.xlsx")]
        public string xlsHotelKadouPath {
            get {
                return ((string)(this["xlsHotelKadouPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hotel2023")]
        public string xlsPasswordHotel {
            get {
                return ((string)(this["xlsPasswordHotel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.51\\SQLEXPRESS,1433;Initial Catalog=JFG_MST;Persist Security" +
            " Info=True;User ID=jfg210915; Password=jfgpass")]
        public string JFG_MSTConnectionString {
            get {
                return ((string)(this["JFG_MSTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020")]
        public string assignYear1 {
            get {
                return ((string)(this["assignYear1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2022")]
        public string assignYear2 {
            get {
                return ((string)(this["assignYear2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2022")]
        public string assignYear3 {
            get {
                return ((string)(this["assignYear3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\ツアー向けガイドリスト2023.xlsx")]
        public string xlsTourGuideListPath {
            get {
                return ((string)(this["xlsTourGuideListPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\ツアー向けガイド稼働予定表.xlsx")]
        public string xlsTourWorksPath {
            get {
                return ((string)(this["xlsTourWorksPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tour2023")]
        public string xlsPasswordTour {
            get {
                return ((string)(this["xlsPasswordTour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Owner\\OneDrive - softbit\\JFG\\20230330稼働予定表\\")]
        public string Copy2OneDrivePath {
            get {
                return ((string)(this["Copy2OneDrivePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\ツアー向けガイドリスト英語以外.xlsx")]
        public string xlsPasswordTourNonEng {
            get {
                return ((string)(this["xlsPasswordTourNonEng"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\ツアー向けガイド英語以外稼働予定表.xlsx")]
        public string xlsTourNotEngWorksPath {
            get {
                return ((string)(this["xlsTourNotEngWorksPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tagengo2023")]
        public string xlsPasswordTourNotEng {
            get {
                return ((string)(this["xlsPasswordTourNotEng"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\西日本_新ホテル向けガイドリスト.xlsx")]
        public string xlsWestHotelGuideListPath {
            get {
                return ((string)(this["xlsWestHotelGuideListPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("newhotel")]
        public string xlsPasswordWestEng {
            get {
                return ((string)(this["xlsPasswordWestEng"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\西日本_新ホテル向け英語ガイド稼働予定表.xlsx")]
        public string xlsWestEngWorksPath {
            get {
                return ((string)(this["xlsWestEngWorksPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\西日本他言語_新ホテル向けガイドリスト.xlsx")]
        public string xlsWestHotelNotEngGuideListPath {
            get {
                return ((string)(this["xlsWestHotelNotEngGuideListPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tagengo")]
        public string xlsPasswordWestNotEng {
            get {
                return ((string)(this["xlsPasswordWestNotEng"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\JFGWORKS\\西日本_新ホテル向け多言語ガイド稼働予定表.xlsx")]
        public string xlsWestNotEngWorksPath {
            get {
                return ((string)(this["xlsWestNotEngWorksPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kadoyoteihyo2024")]
        public string xlsPasswordAll {
            get {
                return ((string)(this["xlsPasswordAll"]));
            }
        }
    }
}
